version: "2"
services:
  haproxy1:
    image: "mminks/haproxy-docker-logging"
    volumes:
      - ./haproxy/haproxy-3.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - "3000:80"
    networks:
      - haproxy-example

  node1:
    image: naturalintmma/express:no-favicon
    user: "node"
    environment:
      - NODE_ENV=production
      - MESSAGE=node1
    ports:
      - "3001:3000"
    networks:
      - haproxy-example


  node2:
    image: naturalintmma/express:no-favicon
    user: "node"
    environment:
      - NODE_ENV=production
      - MESSAGE=node2
    ports:
      - "3002:3000"
    networks:
      - haproxy-example

  node3:
    image: naturalintmma/express:no-favicon
    user: "node"
    environment:
      - NODE_ENV=production
      - MESSAGE=node3
    ports:
      - "3003:3000"
    networks:
      - haproxy-example

networks:
  haproxy-example:

