version: "2"
services:
  haproxy1:
    image: "mminks/haproxy-docker-logging"
    volumes:
      - ./haproxy:/usr/local/etc/haproxy/
    ports:
      - "3000:80"
    networks:
      - haproxy-example

  node1:
    image: naturalintmma/express:latest
    user: "node"
    environment:
      - NODE_ENV=production
      - MESSAGE=node1
    ports:
      - "3001:3000"
    networks:
      - haproxy-example


  node2:
    image: naturalintmma/express:latest
    user: "node"
    environment:
      - NODE_ENV=production
      - MESSAGE=node2
    ports:
      - "3002:3000"
    networks:
      - haproxy-example


networks:
  haproxy-example:

